changed weeks to start with sunday
cse110-sp21-group24/cse110-sp21-group24 pull request #93
Opened 2021-06-08 05:44 UTC by aneesha99

Changes:
- Edited index to start weeks at Sunday
- Edited daily logs page to go from Sunday - Saturday instead of Monday - Sunday

2021-06-09 20:44 UTC, nmasumot approved these changes
Looks Good to Me

2021-06-09 22:57 UTC, lynguyxn approved these changes

2021-06-09 23:00 UTC, lynguyxn requested changes

2021-06-09 23:00 UTC, lynguyxn commented on public/scripts/dailyLog.js
> +days[1].addEventListener('click', () => {
Why is there 2 event listeners for days[1]?

2021-06-10 01:52 UTC, lynguyxn approved these changes

2021-06-10 01:53 UTC, merged